### ISSUE TITLE
btbb_decode_payload in bluetooth_packet.c

### ISSUE THREAD

**Issue by jbmontgomery4** [greatscottgadgets/libbtbb#23]
I am tracing through the lib and stumbled on this found in the btbb_decode_payload function found in bluetooth_packet.c:

		case PACKET_TYPE_EV5:
			/* assuming EV5 but could be 3-EV5 */
			rv = EV5(pkt->clock, pkt);
		case PACKET_TYPE_DM5:
			/* assuming DM5 but could be 2-DH5 */
			rv = DM(pkt->clock, pkt);
			break;

Should there be a break after rv = EV5(pkt->clock, pkt);?

Just wondering.

Thanks,
John Montgomery

**Comment by dominicgs** [comment]
Good catch, yes there certainly should be.

**Comment by dominicgs** [comment]
Fixed in 389f0c6
