### ISSUE TITLE
Install libbtbb issue

### ISSUE THREAD

**Issue by SylvainDR** [greatscottgadgets/libbtbb#48]
fatal: Not a git repository (or any of the parent directories): .git
FATAL Pcap include dirs cannot be found
FATALPcap library cannot be found
-- Looking for pcap_version
-- Looking for pcap_version - not found
-- Looking for pcap_open_dead
-- Looking for pcap_open_dead - not found
-- Looking for pcap_freecode
-- Looking for pcap_freecode - not found
-- Looking for pcap_breakloop
-- Looking for pcap_breakloop - not found
-- Looking for pcap_create
-- Looking for pcap_create - not found
-- Looking for pcap_datalink_name_to_val
-- Looking for pcap_datalink_name_to_val - not found
-- Looking for pcap_datalink_val_to_description
-- Looking for pcap_datalink_val_to_description - not found
-- Looking for pcap_datalink_val_to_name
-- Looking for pcap_datalink_val_to_name - not found
-- Looking for pcap_findalldevs
-- Looking for pcap_findalldevs - not found
-- Looking for pcap_free_datalinks
-- Looking for pcap_free_datalinks - not found
-- Looking for pcap_get_selectable_fd
-- Looking for pcap_get_selectable_fd - not found
-- Looking for pcap_lib_version
-- Looking for pcap_lib_version - not found
-- Looking for pcap_list_datalinks
-- Looking for pcap_list_datalinks - not found
-- Looking for pcap_set_datalink
-- Looking for pcap_set_datalink - not found
-- Looking for pcap_open
-- Looking for pcap_open - not found
-- Looking for pcap_findalldevs_ex
-- Looking for pcap_findalldevs_ex - not found
-- Looking for pcap_createsrcstr
-- Looking for pcap_createsrcstr - not found
-- Could NOT find PCAP (missing:  PCAP_INCLUDE_DIRS PCAP_LIBRARIES)

**Comment by dominicgs** [comment]
Which version is this?
What did you run?
libpcap shouldn't be required, i.e. this should build without it.

**Comment by SylvainDR** [comment]
i'm using the ubuntu 16.04 LTS version

**Comment by dominicgs** [comment]
Which version of libbtbb?

Also, what did you run?

**Comment by SylvainDR** [comment]
libbtbb-2015-10-R1

**Comment by dominicgs** [comment]
In order to help you with this issue I need as much information as possible about what you have done in the lead up to getting this error message.

1) What did you run?
2) Could you paste the full output of the commands?

**Comment by straithe** [comment]
Do you still need assistance?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
