### ISSUE TITLE
Wireshark Help

### ISSUE THREAD

**Issue by josch1** [greatscottgadgets/libbtbb#52]
This is not so much an issue as a question because  i'm fairly new to this, but its possible iv done something wrong.

I was following the instruction on gethub to capure BLE with Wireshark. https://github.com/greatscottgadgets/ubertooth/wiki/Capturing-BLE-in-Wireshark

But for some reason I only see a protocol for PPI ? 
I noticed in the command window it says "Control message unsupported", could that be the problem ?  
If so how can I fix it?
![tmp_pipe](https://cloud.githubusercontent.com/assets/24379631/23491304/76412f84-fecb-11e6-93e5-7987e06ae3a4.jpg)

**Comment by mikeryan** [comment]
See if following the instructions at the end of "Installing" helps (where it says Edit->Preferences):

https://lacklustre.net/bluetooth/wireshark.html

**Comment by josch1** [comment]
Thank you!

 Im assuming the LE LL protocol is the Bluetooth Low Energy Link Layer?


![btleuber](https://cloud.githubusercontent.com/assets/24379631/23536794/5e3d4042-ff95-11e6-8881-e85e4b0d2ca9.jpg)

One more question. For my senior project I have to capture Bluetooth packets from Fitbits, but i'm new to Wireshark, I don't know exactly what i'm looking at just yet. Know any threads or guides that could help me understand the packets details and bytes pane ?

**Comment by straithe** [comment]
Do you still need assistance?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
